//!
//! generated by flatc-zig
//! binary:     gen/home/travis/Downloads/flatbuffers/reflection/reflection.bfbs
//! schema:     /home/travis/Downloads/flatbuffers/reflection/reflection.fbs
//! file ident: //reflection.fbs
//! typename    reflection.Enum
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const reflection = struct {
    const Type = @import("Type.fb.zig").Type;
    const TypeT = @import("Type.fb.zig").TypeT;
    const Enum = @import("Enum.fb.zig").Enum;
    const EnumT = @import("Enum.fb.zig").EnumT;
    const EnumVal = @import("EnumVal.fb.zig").EnumVal;
    const EnumValT = @import("EnumVal.fb.zig").EnumValT;
    const KeyValue = @import("KeyValue.fb.zig").KeyValue;
    const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;
};

pub const Enum = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) reflection.Enum {
        const n = fb.encode.read(u32, buf[offset..]);
        return reflection.Enum.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) reflection.Enum {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return reflection.Enum.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Enum {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Enum) fb.Table {
        return x._tab;
    }

    pub fn Name(rcv: Enum) []const u8 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn KeyCompare(o1: u32, o2: u32, buf: []u8) bool {
        const obj1 = Enum.init(buf, @as(u32, @intCast(buf.len)) - o1);
        const obj2 = Enum.init(buf, @as(u32, @intCast(buf.len)) - o2);
        return std.mem.lessThan(u8, obj1.Name(), obj2.Name());
    }

    pub fn LookupByKey(rcv: *Enum, key: []const u8, vector_loc: u32, buf: []u8) bool {
        var span = fb.encode.read(u32, buf[vector_loc - 4 ..][0..4]);
        var start: u32 = 0;
        while (span != 0) {
            var middle = span / 2;
            const table_off = fb.getIndirectOffset(buf, vector_loc + 4 * (start + middle));
            const obj = Enum.init(buf, table_off);
            const order = std.mem.order(u8, obj.Name(), key);
            if (order == .gt) {
                span = middle;
            } else if (order == .lt) {
                middle += 1;
                start += middle;
                span -= middle;
            } else {
                rcv.* = Enum.init(buf, table_off);
                return true;
            }
        }
        return false;
    }

    pub fn Values(rcv: Enum, j: usize) ?reflection.EnumVal {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return reflection.EnumVal.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn ValuesByKey(rcv: Enum, obj: *reflection.EnumVal, key: i64) bool {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const x = rcv._tab.vector(o);
            return obj.LookupByKey(key, x, rcv._tab.bytes);
        }
        return false;
    }

    pub fn ValuesLen(rcv: Enum) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn IsUnion(rcv: Enum) bool {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.read(bool, o + rcv._tab.pos);
        }
        return false;
    }

    pub fn MutateIsUnion(rcv: Enum, n: bool) bool {
        return rcv._tab.mutateSlot(bool, 8, n);
    }

    pub fn UnderlyingType(rcv: Enum) ?reflection.Type {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return reflection.Type.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn Attributes(rcv: Enum, j: usize) ?reflection.KeyValue {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return reflection.KeyValue.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn AttributesByKey(rcv: Enum, obj: *reflection.KeyValue, key: []const u8) bool {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const x = rcv._tab.vector(o);
            return obj.LookupByKey(key, x, rcv._tab.bytes);
        }
        return false;
    }

    pub fn AttributesLen(rcv: Enum) u32 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn Documentation(rcv: Enum, j: usize) ?[]const u8 {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.byteVector(a + @as(u32, @intCast(j)) * 4);
        }
        return "";
    }

    pub fn DocumentationLen(rcv: Enum) u32 {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// File that this Enum is declared in.
    pub fn DeclarationFile(rcv: Enum) []const u8 {
        const o = rcv._tab.offset(16);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(7);
    }
    pub fn AddName(__builder: *Builder, name: u32) !void {
        try __builder.prependSlotUOff(0, name, 0);
    }

    pub fn AddValues(__builder: *Builder, values: u32) !void {
        try __builder.prependSlotUOff(1, values, 0);
    }

    pub fn StartValuesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddIsUnion(__builder: *Builder, is_union: bool) !void {
        try __builder.prependSlot(bool, 2, is_union, false);
    }

    pub fn AddUnderlyingType(__builder: *Builder, underlying_type: u32) !void {
        try __builder.prependSlotUOff(3, underlying_type, 0);
    }

    pub fn AddAttributes(__builder: *Builder, attributes: u32) !void {
        try __builder.prependSlotUOff(4, attributes, 0);
    }

    pub fn StartAttributesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddDocumentation(__builder: *Builder, documentation: u32) !void {
        try __builder.prependSlotUOff(5, documentation, 0);
    }

    pub fn StartDocumentationVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 4);
    }
    pub fn AddDeclarationFile(__builder: *Builder, declaration_file: u32) !void {
        try __builder.prependSlotUOff(6, declaration_file, 0);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }
};
