//!
//! generated by flatc-zig
//! binary:     gen/home/travis/Downloads/flatbuffers/reflection/reflection.bfbs
//! schema:     /home/travis/Downloads/flatbuffers/reflection/reflection.fbs
//! file ident: //reflection.fbs
//! typename    reflection.EnumVal
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const reflection = struct {
    const Type = @import("Type.fb.zig").Type;
    const TypeT = @import("Type.fb.zig").TypeT;
    const EnumVal = @import("EnumVal.fb.zig").EnumVal;
    const EnumValT = @import("EnumVal.fb.zig").EnumValT;
    const KeyValue = @import("KeyValue.fb.zig").KeyValue;
    const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;
};

pub const EnumVal = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) reflection.EnumVal {
        const n = fb.encode.read(u32, buf[offset..]);
        return reflection.EnumVal.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) reflection.EnumVal {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return reflection.EnumVal.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) EnumVal {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: EnumVal) fb.Table {
        return x._tab;
    }

    pub fn Name(rcv: EnumVal) []const u8 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn Value(rcv: EnumVal) i64 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.read(i64, o + rcv._tab.pos);
        }
        return 0;
    }

    pub fn MutateValue(rcv: EnumVal, n: i64) bool {
        return rcv._tab.mutateSlot(i64, 6, n);
    }

    pub fn KeyCompare(o1: u32, o2: u32, buf: []u8) bool {
        const obj1 = EnumVal.init(buf, @intCast(u32, buf.len) - o1);
        const obj2 = EnumVal.init(buf, @intCast(u32, buf.len) - o2);
        return obj1.Value() < obj2.Value();
    }

    pub fn LookupByKey(rcv: *EnumVal, key: i64, vector_loc: u32, buf: []u8) bool {
        var span = fb.encode.read(u32, buf[vector_loc - 4 ..][0..4]);
        var start: u32 = 0;
        while (span != 0) {
            var middle = span / 2;
            const table_off = fb.getIndirectOffset(buf, vector_loc + 4 * (start + middle));
            const obj = EnumVal.init(buf, table_off);
            const order = std.math.order(obj.Value(), key);
            if (order == .gt) {
                span = middle;
            } else if (order == .lt) {
                middle += 1;
                start += middle;
                span -= middle;
            } else {
                rcv.* = EnumVal.init(buf, table_off);
                return true;
            }
        }
        return false;
    }

    pub fn UnionType(rcv: EnumVal) ?reflection.Type {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return reflection.Type.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn Documentation(rcv: EnumVal, j: usize) ?[]const u8 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.byteVector(a + @intCast(u32, j) * 4);
        }
        return "";
    }

    pub fn DocumentationLen(rcv: EnumVal) u32 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn Attributes(rcv: EnumVal, j: usize) ?reflection.KeyValue {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @intCast(u32, j) * 4;
            x = rcv._tab.indirect(x);
            return reflection.KeyValue.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn AttributesByKey(rcv: EnumVal, obj: *reflection.KeyValue, key: []const u8) bool {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            const x = rcv._tab.vector(o);
            return obj.LookupByKey(key, x, rcv._tab.bytes);
        }
        return false;
    }

    pub fn AttributesLen(rcv: EnumVal) u32 {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(6);
    }
    pub fn AddName(__builder: *Builder, name: u32) !void {
        try __builder.prependSlotUOff(0, name, 0);
    }

    pub fn AddValue(__builder: *Builder, value: i64) !void {
        try __builder.prependSlot(i64, 1, value, 0);
    }

    pub fn AddUnionType(__builder: *Builder, union_type: u32) !void {
        try __builder.prependSlotUOff(3, union_type, 0);
    }

    pub fn AddDocumentation(__builder: *Builder, documentation: u32) !void {
        try __builder.prependSlotUOff(4, documentation, 0);
    }

    pub fn StartDocumentationVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 4);
    }
    pub fn AddAttributes(__builder: *Builder, attributes: u32) !void {
        try __builder.prependSlotUOff(5, attributes, 0);
    }

    pub fn StartAttributesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }
};
