//!
//! generated by flatc-zig
//! binary:     gen/home/travis/Downloads/flatbuffers/reflection/reflection.bfbs
//! schema:     /home/travis/Downloads/flatbuffers/reflection/reflection.fbs
//! file ident: //reflection.fbs
//! typename    reflection.Object
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const reflection = struct {
    const Object = @import("Object.fb.zig").Object;
    const ObjectT = @import("Object.fb.zig").ObjectT;
    const Field = @import("Field.fb.zig").Field;
    const FieldT = @import("Field.fb.zig").FieldT;
    const KeyValue = @import("KeyValue.fb.zig").KeyValue;
    const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;
};

pub const Object = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) reflection.Object {
        const n = fb.encode.read(u32, buf[offset..]);
        return reflection.Object.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) reflection.Object {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return reflection.Object.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Object {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Object) fb.Table {
        return x._tab;
    }

    pub fn Name(rcv: Object) []const u8 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn KeyCompare(o1: u32, o2: u32, buf: []u8) bool {
        const obj1 = Object.init(buf, @intCast(u32, buf.len) - o1);
        const obj2 = Object.init(buf, @intCast(u32, buf.len) - o2);
        return std.mem.lessThan(u8, obj1.Name(), obj2.Name());
    }

    pub fn LookupByKey(rcv: *Object, key: []const u8, vector_loc: u32, buf: []u8) bool {
        var span = fb.encode.read(u32, buf[vector_loc - 4 ..][0..4]);
        var start: u32 = 0;
        while (span != 0) {
            var middle = span / 2;
            const table_off = fb.getIndirectOffset(buf, vector_loc + 4 * (start + middle));
            const obj = Object.init(buf, table_off);
            const order = std.mem.order(u8, obj.Name(), key);
            if (order == .gt) {
                span = middle;
            } else if (order == .lt) {
                middle += 1;
                start += middle;
                span -= middle;
            } else {
                rcv.* = Object.init(buf, table_off);
                return true;
            }
        }
        return false;
    }

    pub fn Fields(rcv: Object, j: usize) ?reflection.Field {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @intCast(u32, j) * 4;
            x = rcv._tab.indirect(x);
            return reflection.Field.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn FieldsByKey(rcv: Object, obj: *reflection.Field, key: []const u8) bool {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const x = rcv._tab.vector(o);
            return obj.LookupByKey(key, x, rcv._tab.bytes);
        }
        return false;
    }

    pub fn FieldsLen(rcv: Object) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn IsStruct(rcv: Object) bool {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.read(bool, o + rcv._tab.pos);
        }
        return false;
    }

    pub fn MutateIsStruct(rcv: Object, n: bool) bool {
        return rcv._tab.mutateSlot(bool, 8, n);
    }

    pub fn Minalign(rcv: Object) i32 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.read(i32, o + rcv._tab.pos);
        }
        return 0;
    }

    pub fn MutateMinalign(rcv: Object, n: i32) bool {
        return rcv._tab.mutateSlot(i32, 10, n);
    }

    pub fn Bytesize(rcv: Object) i32 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            return rcv._tab.read(i32, o + rcv._tab.pos);
        }
        return 0;
    }

    pub fn MutateBytesize(rcv: Object, n: i32) bool {
        return rcv._tab.mutateSlot(i32, 12, n);
    }

    pub fn Attributes(rcv: Object, j: usize) ?reflection.KeyValue {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @intCast(u32, j) * 4;
            x = rcv._tab.indirect(x);
            return reflection.KeyValue.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn AttributesByKey(rcv: Object, obj: *reflection.KeyValue, key: []const u8) bool {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            const x = rcv._tab.vector(o);
            return obj.LookupByKey(key, x, rcv._tab.bytes);
        }
        return false;
    }

    pub fn AttributesLen(rcv: Object) u32 {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn Documentation(rcv: Object, j: usize) ?[]const u8 {
        const o = rcv._tab.offset(16);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.byteVector(a + @intCast(u32, j) * 4);
        }
        return "";
    }

    pub fn DocumentationLen(rcv: Object) u32 {
        const o = rcv._tab.offset(16);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// File that this Object is declared in.
    pub fn DeclarationFile(rcv: Object) []const u8 {
        const o = rcv._tab.offset(18);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(8);
    }
    pub fn AddName(__builder: *Builder, name: u32) !void {
        try __builder.prependSlotUOff(0, name, 0);
    }

    pub fn AddFields(__builder: *Builder, fields: u32) !void {
        try __builder.prependSlotUOff(1, fields, 0);
    }

    pub fn StartFieldsVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddIsStruct(__builder: *Builder, is_struct: bool) !void {
        try __builder.prependSlot(bool, 2, is_struct, false);
    }

    pub fn AddMinalign(__builder: *Builder, minalign: i32) !void {
        try __builder.prependSlot(i32, 3, minalign, 0);
    }

    pub fn AddBytesize(__builder: *Builder, bytesize: i32) !void {
        try __builder.prependSlot(i32, 4, bytesize, 0);
    }

    pub fn AddAttributes(__builder: *Builder, attributes: u32) !void {
        try __builder.prependSlotUOff(5, attributes, 0);
    }

    pub fn StartAttributesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddDocumentation(__builder: *Builder, documentation: u32) !void {
        try __builder.prependSlotUOff(6, documentation, 0);
    }

    pub fn StartDocumentationVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 4);
    }
    pub fn AddDeclarationFile(__builder: *Builder, declaration_file: u32) !void {
        try __builder.prependSlotUOff(7, declaration_file, 0);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }
};
