name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig build -Doptimize=${{ matrix.optimize }}
      - run: zig build test -Doptimize=${{ matrix.optimize }}
      - run: zig build run-sample -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check .
